// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TypeScriptAnalyzerEslintVsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "TypeScriptAnalyzerEslintVsix64.32ed3625-909f-4970-9d47-e0030bc2656f";
        public const string Name = "TypeScript Analyzer (ESLint, Prettier)";
        public const string Description = @"Lints and formats JavaScript and TypeScript files directly in Visual Studio using ESLint and Prettier";
        public const string Language = "en-US";
        public const string Version = "2.1";
        public const string Author = "RN";
        public const string Tags = "Lint,ESLint,Prettier,JavaScript,TypeScript";
    }
}
