// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TypeScriptAnalyzerEslintVsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "45A5655D-42CD-4BB8-82B2-01D177E45B99";
        public const string Name = "TypeScript Analyzer (ESLint, Prettier)";
        public const string Description = @"Lints and formats JavaScript and TypeScript files directly in Visual Studio using ESLint and Prettier";
        public const string Language = "en-US";
        public const string Version = "2.5";
        public const string Author = "RN";
        public const string Tags = "Lint,ESLint,Prettier,JavaScript,TypeScript";
    }
}
