// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TypeScriptAnalyzerEslintVsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSPackageString = "d7c8e95a-d62a-4c10-b4b0-2fb3ba02a47b";
        public static Guid guidVSPackage = new Guid(guidVSPackageString);

        public const string SolutionExplorerGuidString = "a21d2581-a97e-4b22-b776-d5ae7de9bb7d";
        public static Guid SolutionExplorerGuid = new Guid(SolutionExplorerGuidString);

        public const string CodeFileGuidString = "5388b95a-2b18-4c96-8a9f-9f192fed6a3f";
        public static Guid CodeFileGuid = new Guid(CodeFileGuidString);

        public const string ErrorListGuidString = "6fd8152d-849e-49b8-90b2-95ce539c93c9";
        public static Guid ErrorListGuid = new Guid(ErrorListGuidString);

        public const string ToolsMenuGuidString = "24f0f526-4616-4c7a-82ee-f012cf3ab9cb";
        public static Guid ToolsMenuGuid = new Guid(ToolsMenuGuidString);

        public const string guidWorkspaceExplorerToolWindowGuidString = "cfb400f1-5c60-4f3c-856e-180d28def0b7";
        public static Guid guidWorkspaceExplorerToolWindowGuid = new Guid(guidWorkspaceExplorerToolWindowGuidString);

        public const string FolderViewGuidString = "ab48b7da-2de4-4ed4-bf0d-e98489e8aab5";
        public static Guid FolderViewGuid = new Guid(FolderViewGuidString);

        public const string CMDSETID_HtmEdGrp_Dev12String = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public static Guid CMDSETID_HtmEdGrp_Dev12 = new Guid(CMDSETID_HtmEdGrp_Dev12String);

        public const string CMDSETID_HtmEdGrpString = "d7e8c5e1-bdb8-11d0-9c88-0000f8040a53";
        public static Guid CMDSETID_HtmEdGrp = new Guid(CMDSETID_HtmEdGrpString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SolutionExplorerContextMenuGroup = 0x1020;
        public const int LintFilesCommand = 0x0100;
        public const int FixLintErrorsCommand = 0x0150;
        public const int CleanErrorsCommand = 0x0200;
        public const int CodeFileContextMenuGroup = 0x1020;
        public const int LintActiveFileCommand = 0x0100;
        public const int FixActiveFileCommand = 0x0150;
        public const int CodeFileCleanErrorsCommand = 0x0200;
        public const int ErrorListContextMenuGroup = 0x1020;
        public const int ErrorListCleanErrorsCommand = 0x0200;
        public const int ToolsGroup = 0x1010;
        public const int ToolsMenu = 0x1020;
        public const int ToolsMenuGroup = 0x1030;
        public const int ToolsMenuResetGroup = 0x1040;
        public const int ResetConfigFiles = 0x0010;
        public const int EditESLint = 0x0400;
        public const int idmWSE_ContextMenu = 0x0002;
        public const int FolderViewContextMenuGroup = 0x1020;
        public const int FolderViewLintFilesCommand = 0x0101;
        public const int FolderViewFixLintErrorsCommand = 0x0102;
        public const int FolderViewCleanErrorsCommand = 0x0103;
        public const int IDMX_HTM_SOURCE_HTML_Dev12 = 0x0001;
        public const int IDMX_HTM_SOURCE_HTML = 0x0033;
        public const int IDMX_HTM_SOURCE_SCRIPT = 0x0034;
        public const int IDMX_HTM_SOURCE_ASPX = 0x0035;
    }
}