theme: jekyll-theme-slate
title: TypeScript Analyzer (ESLint, Prettier)
description: A linter and formatter for JavaScript and TypeScript in Visual Studio
github: [metadata]

versions:
    devdependencies: |
        "devDependencies": {
            "@types/node": "18.11.18",
            "@typescript-eslint/eslint-plugin": "5.50.0",
            "@typescript-eslint/parser": "5.50.0",
            "eslint": "8.33.0",
            "eslint-plugin-prettier": "4.2.1",
            "prettier": "2.8.3",
            "typescript": "4.9.4"
        }