theme: jekyll-theme-slate
title: TypeScript Analyzer (ESLint, Prettier)
description: A linter and formatter for JavaScript and TypeScript in Visual Studio
github: [metadata]

packageversions:
    typesnode: |- 
        "@types/node": "18.11.18",
    typescripteslintplugin: |-
        "@typescript-eslint/eslint-plugin": "5.50.0",
    typescripteslintparser: |-
        "@typescript-eslint/parser": "5.50.0",
    eslint: |-
        "eslint": "8.33.0",
    elslintpluginprettier: |-
        "eslint-plugin-prettier": "4.2.1",
    prettier: |-
        "prettier": "2.8.3",
    typescript: |-
        "typescript": "4.9.5"
    comma: |-
        ,