theme: jekyll-theme-slate
title: TypeScript Analyzer (ESLint, Prettier)
description: A linter and formatter for JavaScript and TypeScript in Visual Studio
github: [metadata]

packageversions:
    typesnode: |- 
        "@types/node": "20.11.0"
    typescripteslintplugin: |-
        "@typescript-eslint/eslint-plugin": "6.20.0"
    typescripteslintparser: |-
        "@typescript-eslint/parser": "6.20.0"
    eslint: |-
        "eslint": "8.56.0"
    eslintpluginprettier: |-
        "eslint-plugin-prettier": "5.1.3"
    prettier: |-
        "prettier": "3.2.4"
    typescript: |-
        "typescript": "5.3.3"
    eslintpluginjsdoc: |-
        "eslint-plugin-jsdoc": "48.0.4"
    eslintpluginmarkdown: |-
        "eslint-plugin-md": "1.0.19"
    eslintpluginnode: |-
        "eslint-plugin-node": "11.1.0"
    eslintpluginreact: |-
        "eslint-plugin-react": "7.33.2"
    eslintpluginvue: |-
        "eslint-plugin-vue": "9.20.1"
    vueeslintparser: |-
        "vue-eslint-parser": "9.4.2"
    babeleslintparser: |-
        "@babel/eslint-parser": "7.23.9"
    vueeslintconfigtypescript: |-
        "@vue/eslint-config-typescript": "12.0.0"
