theme: jekyll-theme-slate
title: TypeScript Analyzer (ESLint, Prettier)
description: A linter and formatter for JavaScript and TypeScript in Visual Studio
github: [metadata]

packageversions:
    typesnode: |- 
        "@types/node": "18.16.0"
    typescripteslintplugin: |-
        "@typescript-eslint/eslint-plugin": "5.59.5"
    typescripteslintparser: |-
        "@typescript-eslint/parser": "5.59.5"
    eslint: |-
        "eslint": "8.40.0"
    eslintpluginprettier: |-
        "eslint-plugin-prettier": "4.2.1"
    prettier: |-
        "prettier": "2.8.8"
    typescript: |-
        "typescript": "5.0.4"
    eslintpluginjsdoc: |-
        "eslint-plugin-jsdoc": "44.0.2"
    eslintpluginmarkdown: |-
        "eslint-plugin-md": "1.0.19"
    eslintpluginnode: |-
        "eslint-plugin-node": "11.1.0"
    eslintpluginreact: |-
        "eslint-plugin-react": "7.32.2"
    eslintpluginvue: |-
        "eslint-plugin-vue": "9.11.1"
    vueeslintparser: |-
        "vue-eslint-parser": "9.2.1"
    babeleslintparser: |-
        "@babel/eslint-parser": "7.21.8"
    vueeslintconfigtypescript: |-
        "@vue/eslint-config-typescript": "11.0.3"
